simaple-team/simaple

simaple/job/builtin/archmagefb.py
simaple/job/static_property.py
simaple/metric/metric.py
simaple/preset/base.py
tests/job/builtin/test_jobs.py
tests/metric/test_metric.py

feat: remove redundant argument

---

simaple/data/skill/resources/components/magician.yaml
simaple/simulate/component/skill.py
simaple/simulate/component/specific/__init__.py
simaple/simulate/component/specific/magician.py
tests/simulate/component/specific/test_magician.py
tests/simulate/conftest.py
tests/simulate/report/test_dpm.py

feat: add infinity

---

simaple/simulate/base.py
simaple/simulate/component/base.py
simaple/simulate/component/skill.py
simaple/simulate/component/specific/archmagefb.py
tests/simulate/component/specific/test_magician.py
tests/simulate/component/test_buff_component.py
tests/simulate/conftest.py

반환된 state의 개수가 제공된 state의 개수와 일치하지 않을 경우 오류를 발생시킵니다.

feat: raise error when state signature mismatch

---

simaple/data/passive_hyper_skill/__init__.py
simaple/data/passive_hyper_skill/patch.py
simaple/data/passive_hyper_skill/resources/archmagefb.yaml
simaple/data/passive_hyper_skill/spec.py
simaple/data/skill/resources/components/archmagefb.yaml
tests/data/test_passive_hyper_skill.py
tests/simulate/conftest.py

feat: support passive hyper skill

---

simaple/data/doping/__init__.py
simaple/data/doping/doping.yaml
simaple/data/monster_life/__init__.py
simaple/data/monster_life/monster_life_mob.yaml
simaple/system/__init__.py
tests/data/test_doping.py
tests/data/test_monster_life.py

도핑과 몬스터라이프로 인한 상승분을 쉽게 계산할 수 있도록 합니다.
이들 수치는 preset에 포함되지 않습니다.

Add doping, monster life

---

simaple/simulate/component/complex_skill.py
simaple/simulate/component/keydown_skill.py
simaple/simulate/component/specific/archmagetc.py
simaple/simulate/report/base.py
simaple/simulate/view.py
simaple/spec/loadable.py
simaple/spec/patch.py
simaple/spec/repository.py
tests/simulate/component/test_keydown_component.py
tests/simulate/component/test_tick_component.py
tests/simulate/component/util.py
tests/simulate/report/test_level_advantage.py

test: add for coverage

---

README.md
development/adr/template.md
development/readme.md

docs: add documentation about development

---

simaple/simulate/component/view.py

chore: set default value of stack in views

---

simaple/simulate/component/specific/mechanic.py

* set view stack to 0 while not running

fix(mechanic): mech carrier view stack

---

simaple/simulate/component/specific/mechanic.py

* summon multiplier was missing

fix(mechanic): robot duration in running view

---

simaple/container/simulation.py
simaple/core/base.py
simaple/system/trait.py
tests/system/test_trait.py

feat: add character trait

---

simaple/app/domain/history.py
simaple/simulate/actor.py
simaple/simulate/base.py
simaple/simulate/event.py
simaple/simulate/report/base.py
tests/simulate/test_base.py

Event의 모든 객체는 반드시 dict로 저장되도록 합니다.

fix: event as only-dict

---

development/adr/001-dot-damage.md

adr: add adr about dot damage

---

simaple/data/skill/resources/components/archmagefb.yaml
simaple/data/skill/resources/components/mechanic.yaml
simaple/simulate/component/complex_skill.py
simaple/simulate/component/keydown_skill.py
simaple/simulate/component/skill.py
simaple/simulate/component/specific/archmagetc.py
simaple/simulate/component/specific/mechanic.py
simaple/simulate/component/triggable_buff_skill.py

refactor: remove component default cooldown

---

simaple/app/domain/simulator_configuration.py
simaple/data/passive/resources/passive_skill/adele.yaml
simaple/data/skill/resources/components/classes/pirate.yaml
tests/simulate/report/adele/conftest.py
tests/simulate/report/mechanic/conftest.py

refactor: rename weapon_attack_power to weapon_pure_attack_power

---

simaple/data/skill/resources/components/archmagefb.yaml
simaple/simulate/component/keydown_skill.py
simaple/simulate/component/specific/archmagefb.py
simaple/simulate/component/specific/archmagetc.py

Component 생성 인자에 대입된 default value를 제거합니다.
Closes #98

feat: no default value in component definition

---

simaple/data/skill/resources/components/common_v.yaml
simaple/simulate/component/specific/__init__.py
simaple/simulate/component/specific/common_v.py
tests/simulate/component/test_common_v.py
tests/simulate/report/archmagefb/conftest.py

공용 쓸스킬과 스인미, 크오솔을 추가합니다.
Closes #79

feat: add v skills

---

simaple/data/skill/resources/components/genesis.yaml
simaple/simulate/component/skill.py
tests/simulate/component/test_always_enabled_component.py

파괴 스킬과, 항상 발동되는 스킬 컴포넌트를 추가합니다.

feat: add genesis skill (destroy)

---

simaple/data/skill/resources/components/adele.yaml
simaple/data/skill/resources/components/archmagefb.yaml
simaple/data/skill/resources/components/dualblade.yaml
simaple/simulate/component/base.py
simaple/simulate/component/specific/adele.py
simaple/simulate/component/specific/archmagefb.py
simaple/simulate/component/specific/dualblade.py
tests/simulate/test_parametrized_reducer.py

Reducer에 static payload를 reserve해서 listen할 수 있도록 합니다.

feat: parametrized reducer

---

simaple/data/skill/resources/components/flora.yaml
simaple/simulate/component/entity.py
simaple/simulate/component/skill.py
simaple/simulate/component/specific/flora.py
simaple/simulate/component/state_protocol.py
simaple/simulate/component/trait/impl.py
tests/simulate/component/specific/test_flora.py
tests/simulate/component/test_consumable_buff_component.py
tests/simulate/report/adele/test_adele.py

* 매직 서킷 풀드라이브 컴포넌트
* 그란디스 여신의 축복(레프)
* ConsumableBuffSkillComponent
* 사용 횟수가 스택으로 누적 가능한 버프 컴포넌트
* ConsumableState, ConsumableDurableTrait을 사용

feat: flora common skills

---

development/event.md
simaple/simulate/component/base.py
simaple/simulate/reserved_names.py

Accept event를 추가합니다.
이 이벤트는 대부분의 경우에 콜백 목적으로 활용될 수 있습니다.

feat: add accept event

---

simaple/data/skill/resources/components/archmagefb.yaml

fix: unused field type

---

docs/modules/simulate_en.rst
docs/modules/tutorial/tutorial-en.rst

also includes typo fixes for tutorial-en.rst

simulate-en.rst translation

---

.gitignore
simaple/simulate/component/entity.py
simaple/simulate/component/specific/adele.py
simaple/simulate/component/specific/archmagefb.py
simaple/simulate/component/specific/dualblade.py
simaple/simulate/component/specific/soulmaster.py
simaple/simulate/component/trait/impl.py

Cooldown 관련 동작을 method로 추출하여 코드 중복을 피하고, 변수에 대한 직접 접근을 방지합니다.

Extract cooldown related methods

---

scripts/debug.py
scripts/repl.py
scripts/show_dpm.py
simaple/container/simulation.py
simaple/simulate/interface/simulator_configuration.py
test_data/test_container_runtime.py
tests/simulate/policy/test_dsl_runtime.py

Seperate dependency to isolate container as pure python code

refactor: use pure python dep injector

---

webui/package.json
webui/src/hooks/useWorkspace.tsx
webui/src/pages/Editor.tsx
webui/yarn.lock

더 나은 편집 경험을 위해 Codemirror를 도입하고, 스킬 이름 자동 완성을 제공합니다.

feat(webui): use codemirror for plan editing

---

simaple/wasm/__init__.py
simaple/wasm/workspace.py
tests/wasm/test_workspace.py
webui/package.json
webui/src/Router.tsx
webui/src/components/Chart.tsx
webui/src/components/CreateBaselineSimulatorDialog.tsx
webui/src/hooks/useChart.tsx
webui/src/hooks/useSimaple.tsx
webui/src/hooks/useWorkspace.tsx
webui/src/hooks/useWorkspaceState.tsx
webui/src/pages/Editor.tsx
webui/src/sdk/index.ts
webui/yarn.lock

feat: wasm stateless protocol

---

webui/README.md
webui/package.json
webui/src/sdk/index.ts
webui/yarn.lock

- 모듈 로드를 병렬화해 Pyodide 초기화 속도를 개선합니다.
- 로컬에서 빌드된 wheel을 로드해올 수 있는 개발 서버를 추가해 개발 경험을 개선합니다.

perf: faster python package load

---

webui/src/sdk/index.ts

고정 도메인이 아닌 본인의 origin에서 wheel을 가져오도록 합니다.

feat(webui): get simaple wheel from self origin

---

webui/README.md
webui/package.json
webui/src/sdk/index.ts
webui/yarn.lock

별도의 개발 서버 없이 simaple whl을 가져올 수 있도록 webui 개발 환경을 개선합니다.

chore(webui): serve whl without seperate dev server

---

webui/src/components/ChartSettingDialog.tsx
webui/src/hooks/preferences.interface.ts
webui/src/hooks/useChart.tsx
webui/src/hooks/usePreference.tsx

Running view에 대응되는 차트에서 추적할 스킬 이름을 직접 선택할 수 있도록 옵션을 추가합니다.

feat(webui): add skill names option to running view chart

---

gen/jsonschema/OperationLogResponse.schema.json
simaple/core/base.py
simaple/simulate/base.py
simaple/simulate/component/view.py
simaple/simulate/policy/base.py
simaple/simulate/report/base.py
simaple/wasm/models/simulation.py
tests/simulate/component/specific/test_bishop.py
tests/simulate/policy/test_history.py
tests/simulate/test_damage_calculator.py
webui/src/sdk/models/OperationLogResponse.schema.d.ts

Resolve https://maplestorydpmcalc.slack.com/archives/C01H9RASRGR/p1726809971505739
정의되지 않은 필드에 접근하지 못하게 막습니다.

feat: disallow unspecified fields

---

webui/src/App.tsx
webui/src/components/ChartSettingDialog.tsx
webui/src/components/CreateBaselineSimulatorDialog.tsx
webui/src/components/Editor.tsx
webui/src/components/Header.tsx
webui/src/hooks/useChart.tsx
webui/src/lib/formatters.ts
webui/src/pages/ChartPage.tsx
webui/src/pages/EditorLayout.tsx
webui/src/pages/LogPage.tsx
webui/src/pages/PrepareSimaple.tsx
webui/src/pages/SummaryPage.tsx
webui/src/statistics/index.ts

- 전투분석 뷰 추가
- 헤더에 있던 버튼들을 각 기능 영역으로 분배
- 로그뷰 고도화
- 차트뷰는 별도 작업으로 개선할 예정

feat(webui): improved ui

---

simaple/wasm/examples.py

일부 환경에서 인코딩 오류가 발생하는 것을 방지합니다.

fix: specify encoding on example plan open

---

simaple/container/simulation.py
tests/container/test_simulation.py

[T-71](https://height.app/gtoFuPGCir/T-71) environment.character에 헥사 강화를 스킬별로 적용할 수 있게 하기

T-71 environment.character에 헥사 강화를 스킬별로 적용할 수 있게 하기

---

webui/src/components/SkillIcon.tsx
webui/src/components/UptimeChart.tsx
webui/src/hooks/useWorkspaceState.tsx
webui/src/pages/LogPage.tsx
webui/src/pages/SummaryPage.tsx

- 로그뷰에 데미지 정보 추가
- 로그뷰에 아이콘 추가
- 로그뷰에 "계산 후 마지막 로그 자동으로 선택" 옵션 추가
- 로그뷰 쿨타임에 필요한 스킬들만 나오도록 필터링
- 로그뷰 지속시간에 지속시간이 적게 남은 스킬부터 보이도록 정렬

feat(webui): better log view

---

simaple/data/jobs/resources/archmagefb/components.yaml
simaple/data/jobs/resources/archmagetc/components.yaml
simaple/data/jobs/resources/mechanic/components.yaml

불독, 썬콜, 메카닉 스킬 데이터에서 더이상 사용되지 않는 필드들을 제거합니다.

refactor: remove unused data

---

webui/src/pages/LogPage.tsx

```
Warning: validateDOMNesting(...): <th> cannot appear as a child of <thead>.
```
경고를 수정합니다.

fix: log page table dom nesting

---

simaple/data/jobs/resources/components/adventurer.yaml
simaple/data/jobs/resources/components/common.yaml
simaple/data/jobs/resources/components/resistance.yaml
test_data/target.py
tests/simulate/policy/test_dsl_runtime.py

소울 컨트랙트의 딜레이가 제거된 것을 반영합니다.
메이플월드 여신의 축복 쿨타임이 120초로 변경된 것을 반영합니다.

fix: apply kms buff changes

---

webui/package.json
webui/src/App.tsx
webui/src/components/ErrorDialog.tsx
webui/src/components/ui/switch.tsx
webui/src/pages/LogPage/LogPage.tsx
webui/src/pages/LogPage/Table.tsx
webui/yarn.lock

로그뷰에 특정 스킬의 데미지가 발생한 로그만 강조하는 기능을 추가합니다.

feat(webui): add skillname highlight in log view

---

webui/package.json
webui/src/App.tsx
webui/src/components/ui/popover.tsx
webui/src/pages/ChartPage/CumulativeDamageChart.tsx
webui/src/pages/ChartPage/IntervalDamageChart.tsx
webui/src/pages/ChartPage/StackChart.tsx
webui/src/pages/ChartPage/UptimeChart.tsx
webui/src/pages/EditorLayout.tsx
webui/src/pages/PreferencePopover.tsx
webui/yarn.lock

- 차트가 너무 넓어지지 않도록 최대 너비 추가
- 지속시간 차트의 X축 범위가 다른 차트와 동일하게 동작하도록 변경
- 측정 구간 설정을 Popover로 변경

feat: webui enhancements

---

webui/src/components/Editor.tsx

잘못된 스킬 이름이 입력되어 있는 경우 lint error를 표기합니다.

feat(webui): lint error on wrong skill name

---

webui/src/sdk/dev.ts

webui dev mode에서 요청 형식이 잘못된 것을 수정합니다.

fix(webui): dev sdk request body

---

simaple/data/baseline/patch.py
simaple/data/jobs/patch.py
simaple/data/jobs/resources/adele/components.yaml
simaple/data/jobs/resources/archmagefb/components.yaml
simaple/data/jobs/resources/archmagetc/components.yaml
simaple/data/jobs/resources/bishop/components.yaml
simaple/data/jobs/resources/dualblade/components.yaml
simaple/data/jobs/resources/mechanic/components.yaml
simaple/data/jobs/resources/windbreaker/components.yaml
simaple/simulate/policy/handlers.py
simaple/spec/patch.py
simaple/spec/spec.py

[T-87](https://height.app/gtoFuPGCir/T-87) 한 스킬의 레벨이 다른 스킬의 레벨을 따라가도록 데이터에 선언할 수 있게 하기

[T-87] support skill level reference specification for each patch

---

simaple/data/baseline/patch.py
simaple/data/jobs/builtin.py
simaple/data/jobs/patch.py
simaple/data/jobs/resources/archmagetc/components.yaml
simaple/spec/patch.py
tests/api/test_workspace.py
tests/data/test_skill_improvement.py

[T-95](https://height.app/gtoFuPGCir/T-95) SkillAdditiveImprovement에서 없는 스킬을 강화하려고 하면 터트리기

[T-95] feat: raise ValueError when no improvement matches

---

scripts/rank.py

feat: add ranking script
